language: csharp
solution: Octree.sln

jobs:
  include:
    - name: ".NET Core"
      dotnet: 2.1
      mono: none
      install:
         - dotnet restore
      script:
         - dotnet build --framework netstandard2.0 --configuration Release
    - name: "Mono Framework"
      mono: latest
      # use default install and script
